import {
  MdLibraryMusic,
  MdOutlineCircle,
  MdStackedBarChart,
  MdOutlineNoteAdd,
  MdArrowBack,
  MdArrowForward,
  MdSearch,
  MdDeleteOutline,
  MdFavorite,
  MdFavoriteBorder,
  MdMoreHoriz,
  MdRepeat,
  MdSkipNext,
  MdSkipPrevious,
  MdShuffle,
  MdPlayArrow,
  MdPause,
  MdAudiotrack,
  MdAdjust,
  MdOutlineRepeatOne,
} from "react-icons/md";

const icons = {
  MdLibraryMusic,
  MdOutlineCircle,
  MdStackedBarChart,
  MdOutlineNoteAdd,
  MdArrowBack,
  MdArrowForward,
  MdSearch,
  MdDeleteOutline,
  MdFavorite,
  MdFavoriteBorder,
  MdMoreHoriz,
  MdRepeat,
  MdSkipNext,
  MdSkipPrevious,
  MdShuffle,
  MdPlayArrow,
  MdPause,
  MdAudiotrack,
  MdAdjust,
  MdOutlineRepeatOne,
};

export default icons;
